[custom.all.idris2-Universe-Wiki]
type = "local"
path = "../idris2-Universe-Wiki"
ipkg = "idris2-Universe-Wiki.ipkg"

[custom.all.idris2-Universe]
type = "local"
path = "../idris2-Universe"
ipkg = "idris2-Universe.ipkg"

[custom.all.Idris2-Universe2]
type = "local"
path = "../Idris2-Universe2"
ipkg = "Idris2-Universe2.ipkg"


[custom.all.idris2-chromogeometry]
type = "local"
path = "../idris2-Chromogeometry"
ipkg = "idris2-chromogeometry.ipkg"

[custom.all.idris2-Multiset]
type = "local"
path = "../idris2-Multiset"
ipkg = "idris2-Multiset.ipkg"

[custom.all.idris2-Dihedron]
type = "local"
path = "../idris2-Dihedron"
ipkg = "idris2-Dihedron.ipkg"

[custom.all.idris2-ref1]
type = "local"
path = "../Library/Src/idris2-ref1"
ipkg = "ref1.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.Idris2-Multiset-Binary]
type = "local"
path = "../Idris2-Multiset-Binary"
ipkg = "Idris2-Multiset-Binary.ipkg"

[custom.all.idris2-Substrate]
type = "local"
path = "../idris2-Substrate"
ipkg = "idris2-Substrate.ipkg"

[custom.all.idris2-Electromagnetism]
type = "local"
path = "../idris2-Electromagnetism"
ipkg = "idris2-Electromagnetism.ipkg"

[custom.all.Idris2-GeoLinAlg]
type = "local"
path = "../Idris2-GeoLinAlg"
ipkg = "Idris2-GeoLinAlg.ipkg"
